#!/usr/bin/env sh
[ -n "$CI" ] && exit 0

echo "Checking diff snapshot..."
make snapshot

delta="$( git ls-files --others --modified --deleted --exclude-standard ./internal/diff/ )"

if [ -z "$delta" ]
then
  echo "Everything up-to-date."
else
  echo "🚧 Snapshot updated."
  echo "$delta"
  git add ./internal/diff/
fi
