#!/usr/bin/env sh
[ -n "$CI" ] && exit 0

. "$(dirname -- "$0")/_/husky.sh"

echo "Checking diff snapshot..."
make snapshot

if [ -z "$( git ls-files --others --modified --deleted --exclude-standard ./internal/diff/ )" ]
then
  echo "Everything up-to-date."
else
  echo "🚧 Snapshot updated."
  git add ./internal/diff/
fi
