name: react

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  chore:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JS
        uses: ./.github/actions/js-setup

      - name: Prettier
        run: npm run prettier:check

      - name: Snapshot
        run: make snapshot

      - name: Check Git
        uses: ./.github/actions/git-check

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    needs:
      - matrixize

    strategy:
      matrix:
        module: ${{ fromJSON(needs.matrixize.outputs.data) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JS
        uses: ./.github/actions/js-setup

      - name: Build
        run: npm run build
        working-directory: "./${{ matrix.module }}"

      - name: Check Git
        uses: ./.github/actions/git-check

  matrixize:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    outputs:
      data: "${{ steps.matrixize.outputs.data }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Matrixize
        id: matrixize
        run: |
          data=$( make matrixize )
          echo "$data"
          echo "data=$data" >> "$GITHUB_OUTPUT"
