name: js

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: "./.nvmrc"

      - name: Activate corepack
        run: corepack enable

      - name: Install dependencies
        run: make install-ci

      - name: Prettier
        run: npm run prettier:check

      - name: Snapshot
        run: make snapshot

      - name: Build
        run: make for-each COMMAND="npm run build"

      - name: Check Git
        uses: ./.github/actions/git-check
