name: warmup

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 11 * * *" # 11am UTC / 4am PT
  workflow_dispatch:

jobs:
  warmup:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Warm up sandboxes
        run: make warmup

      - name: Check Git
        uses: ./.github/actions/git-check
