name: warmup

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 11 * * *" # 11am UTC / 4am PT
  workflow_dispatch:

jobs:
  warmup:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Warm up sandboxes
        run: make warmup

      - name: Check Git
        uses: ./.github/actions/git-check
