name: warmup

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 11 * * *" # 11am UTC / 4am PT
  workflow_dispatch:

jobs:
  warmup:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Warm up sandboxes
        run: make warmup

      - name: Check Git
        uses: ./.github/actions/git-check
